---
layout: cv
title: Jason Rao's CV
---
# Jason Rao
Computer Science Student

<div id="webaddress">
<a href="mailto:jasonrao@byui.edu">jasonrao@byui.edu</a>
| <a href="https://www.linkedin.com/in/yujie-rao">LinkedIn</a>
| <a href="https://github.com/ryjason">GitHub</a>
</div>


## Currently

Pursuing a Bachelor’s degree in Computer Science with a minor in Data Science and Virtual Art.

### Specialized in

Software development, data analysis, and web development.

### Skills

- **Programming Languages:** Python, C#, Java, JavaScript, HTML, CSS, SQL
- **Languages:** Chinese, English, Spanish
- **Other:** Leadership, management, teamwork, customer service


## Education

`January 2023 - Present`
__Brigham Young University - Idaho__, Rexburg, ID  
- Bachelor of Science in Computer Science  
- Minor in Data Science, GPA: 4.0

`January 2021 - December 2023`
__Brigham Young University - Hawaii__, Laie, HI 
- Bachelor of Science in Computer Science  
- Minor in Virtual Art and Entrepreneurship, GPA: 3.78


## Work Experience

`October 2023 – Present`
__Customer Services Representative__, Brigham Young University - Idaho, University Operations, Rexburg, ID  
- Lead phone inquiries and build work orders to support university operations.

`June 2022 – July 2023`
__Stage Manager__, Brigham Young University Hawaii, McKay Auditorium  
- Oversaw backstage operations during performances, ensuring technical elements run smoothly.

`June 2022 – December 2022`
__Vice President of China Club__, Brigham Young University - Hawaii, Laie, Hawaii  
- Led a club of over 120 members, coordinating events and managing communications.

`September 2021 - June 2022`
__Customer Services Representative__, Brigham Young University - Hawaii, Facilities Management, Laie, Hawaii  
- Managed incoming calls and created work orders to support university facilities operations.

`September 2018 - June 2020`
__Yearbook Editor in Chair__, Academia Juarez - High School, Chihuahua, Mexico  
- Led a yearbook team of 12 to create a comprehensive annual publication showcasing school events and student life.


## Projects

`February 2022`
**Game (Hunter and Beast)** - Java, OOP

`January 2023`
**Digital ID** - SDLC, Market Research

`October 2024`
**Personal Website** - HTML, CSS, JS

`January 2024`
**Student Record System** - Python, MySQL, Firebase

`April 2024`
**Color To-Do** - React Native, Firebase, AWS


<!-- ### Footer

Last updated: October 2024 -->